---
source: external-crates/move/crates/move-transactional-test-runner/src/framework.rs
---
processed 7 tasks

init:
A: object(0,0)

task 1, lines 9-48:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7493600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 50-52:
//# programmable --sender A --inputs @A
//> test::m::a();
//> sui::transfer::public_transfer<test::m::A>(Result(0), Input(0));
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2196400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4, lines 56-58:
//# programmable --sender A --inputs @a
//> test::m::a();
//> sui::transfer::public_transfer<test::m::A>(Result(0), Input(0));
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2196400,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5, lines 60-68:
//# programmable --sender A --inputs @0
// valid since pure args are distinct per type usage
//> 0: test::m::heat_val<address>(Input(0));
//> 1: test::m::heat_imm<address>(Input(0));
//> 2: test::m::heat_mut<address>(Input(0));
//> test::m::play_u256(Input(0));
//> test::m::cool(NestedResult(0, 1));
//> test::m::cool(Result(1));
//> test::m::cool(Result(2));
Error: Transaction Effects Status: Invalid command argument at 0. Invalid argument to private entry function. These functions cannot take arguments from other Move functions
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: InvalidArgumentToPrivateEntryFunction }, source: None, command: Some(3) } }

task 6, lines 70-74:
//# programmable --sender A --inputs receiving(4,0)
// valid since receiving args are distinct per type usage
//> 0: test::m::heat_imm<sui::transfer::Receiving<test::m::B>>(Input(0));
//> test::m::play_receiving(Input(0));
//> test::m::cool(Result(0));
Error: Transaction Effects Status: Invalid command argument at 0. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: TypeMismatch }, source: None, command: Some(1) } }
